spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/test
    driverClassName: org.mariadb.jdbc.Driver
    username: jo
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
      show-sql: true
server:
  port: 8080
